project:
  type: website
  resources:
    - "*.html"
  output-dir: docs

website:
  title: "Varada Kolhatkar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching                      
      - href: contact.qmd
        text: Contact      
format:
  html:
    theme: [zephyr]    
    toc: false
    includes:
      in_header: styles.css    
    lightbox: true
          
editor:
  render-on-save: true

execute:
  freeze: auto

